const bancoQuestoes = [
    
// ==========================================
    // ENEM 2025 (Caderno Azul - Matemática)
    // ==========================================
    { id: 136, ano: 2025, gabarito: "C", dificuldade: "facil", tema: "Razões e Proporções" },
    { id: 137, ano: 2025, gabarito: "B", dificuldade: "media", tema: "Estatística" },
    { id: 138, ano: 2025, gabarito: "E", dificuldade: "dificil", tema: "Geometria Espacial" },
    { id: 139, ano: 2025, gabarito: "C", dificuldade: "media", tema: "Matemática Financeira" },
    { id: 140, ano: 2025, gabarito: "E", dificuldade: "facil", tema: "Aritmética Básica" },
    { id: 141, ano: 2025, gabarito: "C", dificuldade: "media", tema: "Funções" },
    { id: 142, ano: 2025, gabarito: "C", dificuldade: "dificil", tema: "Probabilidade" },
    { id: 143, ano: 2025, gabarito: "A", dificuldade: "media", tema: "Geometria Plana" },
    { id: 144, ano: 2025, gabarito: "D", dificuldade: "facil", tema: "Razões e Proporções" },
    { id: 145, ano: 2025, gabarito: "D", dificuldade: "media", tema: "Estatística" },
    { id: 146, ano: 2025, gabarito: "B", dificuldade: "dificil", tema: "Análise Combinatória" },
    { id: 147, ano: 2025, gabarito: "E", dificuldade: "media", tema: "Progressão Aritmética / Geométrica" },
    { id: 148, ano: 2025, gabarito: "C", dificuldade: "facil", tema: "Grandezas e Medidas" },
    { id: 149, ano: 2025, gabarito: "B", dificuldade: "media", tema: "Geometria Analítica" },
    { id: 150, ano: 2025, gabarito: "D", dificuldade: "dificil", tema: "Função Quadrática" },
    { id: 151, ano: 2025, gabarito: "D", dificuldade: "facil", tema: "Matemática Financeira" },
    { id: 152, ano: 2025, gabarito: "D", dificuldade: "media", tema: "Estatística" },
    { id: 153, ano: 2025, gabarito: "A", dificuldade: "media", tema: "Geometria Espacial" },
    { id: 154, ano: 2025, gabarito: "C", dificuldade: "facil", tema: "Razões e Proporções" },
    { id: 155, ano: 2025, gabarito: "B", dificuldade: "dificil", tema: "Probabilidade" },
    { id: 156, ano: 2025, gabarito: "E", dificuldade: "media", tema: "Funções" },
    { id: 157, ano: 2025, gabarito: "C", dificuldade: "facil", tema: "Aritmética" },
    { id: 158, ano: 2025, gabarito: "C", dificuldade: "media", tema: "Geometria Plana" },
    { id: 159, ano: 2025, gabarito: "D", dificuldade: "dificil", tema: "Matemática Financeira" },
    { id: 160, ano: 2025, gabarito: "E", dificuldade: "facil", tema: "Estatística" },
    { id: 161, ano: 2025, gabarito: "A", dificuldade: "media", tema: "Razões e Proporções" },
    { id: 162, ano: 2025, gabarito: "B", dificuldade: "media", tema: "Geometria Espacial" },
    { id: 163, ano: 2025, gabarito: "B", dificuldade: "dificil", tema: "Trigonometria" },
    { id: 164, ano: 2025, gabarito: "A", dificuldade: "facil", tema: "Aritmética" },
    { id: 165, ano: 2025, gabarito: "D", dificuldade: "media", tema: "Probabilidade" },
    { id: 166, ano: 2025, gabarito: "E", dificuldade: "facil", tema: "Geometria Plana" },
    { id: 167, ano: 2025, gabarito: "D", dificuldade: "media", tema: "Função Afim" },
    { id: 168, ano: 2025, gabarito: "E", dificuldade: "dificil", tema: "Geometria Analítica" },
    { id: 169, ano: 2025, gabarito: "A", dificuldade: "facil", tema: "Estatística" },
    { id: 170, ano: 2025, gabarito: "B", dificuldade: "media", tema: "Razões e Proporções" },
    { id: 171, ano: 2025, gabarito: "E", dificuldade: "media", tema: "Matemática Financeira" },
    { id: 172, ano: 2025, gabarito: "A", dificuldade: "facil", tema: "Geometria Espacial" },
    { id: 173, ano: 2025, gabarito: "A", dificuldade: "dificil", tema: "Probabilidade" },
    // Questão 174 ANULADA em 2025 - Removida do banco
    { id: 175, ano: 2025, gabarito: "C", dificuldade: "facil", tema: "Aritmética" },
    { id: 176, ano: 2025, gabarito: "C", dificuldade: "media", tema: "Geometria Plana" },
    { id: 177, ano: 2025, gabarito: "B", dificuldade: "dificil", tema: "Estatística Avançada" },
    { id: 178, ano: 2025, gabarito: "E", dificuldade: "facil", tema: "Razões e Proporções" },
    { id: 179, ano: 2025, gabarito: "A", dificuldade: "media", tema: "Geometria Espacial" },
    { id: 180, ano: 2025, gabarito: "D", dificuldade: "dificil", tema: "Logaritmos" },

    // ==========================================
    // ENEM 2024 (Caderno Amarelo - Matemática)[cite: 3]
    // ==========================================
    { id: 136, ano: 2024, gabarito: "C", dificuldade: "facil", tema: "Razões e Proporções" },
    { id: 137, ano: 2024, gabarito: "E", dificuldade: "media", tema: "Estatística Básica" },
    { id: 138, ano: 2024, gabarito: "C", dificuldade: "dificil", tema: "Geometria Espacial" },
    { id: 139, ano: 2024, gabarito: "E", dificuldade: "media", tema: "Matemática Financeira" },
    { id: 140, ano: 2024, gabarito: "B", dificuldade: "facil", tema: "Aritmética Básica" },
    { id: 141, ano: 2024, gabarito: "E", dificuldade: "media", tema: "Função Afim" },
    { id: 142, ano: 2024, gabarito: "D", dificuldade: "dificil", tema: "Probabilidade" },
    { id: 143, ano: 2024, gabarito: "A", dificuldade: "media", tema: "Geometria Plana" },
    { id: 144, ano: 2024, gabarito: "D", dificuldade: "facil", tema: "Razões e Proporções" },
    { id: 145, ano: 2024, gabarito: "C", dificuldade: "media", tema: "Estatística" },
    { id: 146, ano: 2024, gabarito: "A", dificuldade: "dificil", tema: "Análise Combinatória" },
    { id: 147, ano: 2024, gabarito: "A", dificuldade: "media", tema: "Progressão Aritmética / Geométrica" },
    { id: 148, ano: 2024, gabarito: "D", dificuldade: "facil", tema: "Grandezas e Medidas" },
    { id: 149, ano: 2024, gabarito: "E", dificuldade: "media", tema: "Geometria Analítica" },
    { id: 150, ano: 2024, gabarito: "C", dificuldade: "dificil", tema: "Função Quadrática" },
    { id: 151, ano: 2024, gabarito: "D", dificuldade: "facil", tema: "Matemática Financeira" },
    { id: 152, ano: 2024, gabarito: "B", dificuldade: "media", tema: "Estatística" },
    { id: 153, ano: 2024, gabarito: "B", dificuldade: "media", tema: "Geometria Espacial" },
    { id: 154, ano: 2024, gabarito: "C", dificuldade: "facil", tema: "Razões e Proporções" },
    { id: 155, ano: 2024, gabarito: "E", dificuldade: "dificil", tema: "Probabilidade" },
    { id: 156, ano: 2024, gabarito: "B", dificuldade: "media", tema: "Funções" },
    { id: 157, ano: 2024, gabarito: "D", dificuldade: "facil", tema: "Aritmética" },
    { id: 158, ano: 2024, gabarito: "C", dificuldade: "media", tema: "Geometria Plana" },
    { id: 159, ano: 2024, gabarito: "C", dificuldade: "dificil", tema: "Matemática Financeira" },
    { id: 160, ano: 2024, gabarito: "C", dificuldade: "facil", tema: "Estatística" },
    { id: 161, ano: 2024, gabarito: "A", dificuldade: "media", tema: "Razões e Proporções" },
    { id: 162, ano: 2024, gabarito: "C", dificuldade: "media", tema: "Geometria Espacial" },
    { id: 163, ano: 2024, gabarito: "A", dificuldade: "dificil", tema: "Trigonometria" },
    { id: 164, ano: 2024, gabarito: "B", dificuldade: "facil", tema: "Aritmética" },
    { id: 165, ano: 2024, gabarito: "B", dificuldade: "media", tema: "Probabilidade" },
    { id: 166, ano: 2024, gabarito: "A", dificuldade: "facil", tema: "Geometria Plana" },
    { id: 167, ano: 2024, gabarito: "B", dificuldade: "media", tema: "Função Afim" },
    { id: 168, ano: 2024, gabarito: "B", dificuldade: "dificil", tema: "Geometria Analítica" },
    { id: 169, ano: 2024, gabarito: "A", dificuldade: "facil", tema: "Estatística" },
    { id: 170, ano: 2024, gabarito: "D", dificuldade: "media", tema: "Razões e Proporções" },
    { id: 171, ano: 2024, gabarito: "D", dificuldade: "media", tema: "Matemática Financeira" },
    { id: 172, ano: 2024, gabarito: "D", dificuldade: "facil", tema: "Geometria Espacial" },
    { id: 173, ano: 2024, gabarito: "C", dificuldade: "dificil", tema: "Probabilidade" },
    { id: 174, ano: 2024, gabarito: "E", dificuldade: "facil", tema: "Aritmética" },
    { id: 175, ano: 2024, gabarito: "A", dificuldade: "media", tema: "Funções" },
    { id: 176, ano: 2024, gabarito: "D", dificuldade: "media", tema: "Geometria Plana" },
    { id: 177, ano: 2024, gabarito: "B", dificuldade: "dificil", tema: "Estatística Avançada" },
    { id: 178, ano: 2024, gabarito: "B", dificuldade: "facil", tema: "Razões e Proporções" },
    { id: 179, ano: 2024, gabarito: "C", dificuldade: "media", tema: "Geometria Espacial" },
    { id: 180, ano: 2024, gabarito: "E", dificuldade: "dificil", tema: "Logaritmos" },

    // ==========================================
    // ENEM 2023 (Caderno Amarelo - Matemática)[cite: 5]
    // ==========================================
    { id: 136, ano: 2023, gabarito: "D", dificuldade: "facil", tema: "Razões e Proporções" },
    { id: 137, ano: 2023, gabarito: "C", dificuldade: "media", tema: "Estatística Básica" },
    { id: 138, ano: 2023, gabarito: "E", dificuldade: "dificil", tema: "Geometria Espacial" },
    { id: 139, ano: 2023, gabarito: "C", dificuldade: "media", tema: "Matemática Financeira" },
    { id: 140, ano: 2023, gabarito: "A", dificuldade: "facil", tema: "Aritmética Básica" },
    { id: 141, ano: 2023, gabarito: "C", dificuldade: "media", tema: "Função Afim" },
    { id: 142, ano: 2023, gabarito: "C", dificuldade: "dificil", tema: "Probabilidade" },
    { id: 143, ano: 2023, gabarito: "B", dificuldade: "media", tema: "Geometria Plana" },
    { id: 144, ano: 2023, gabarito: "D", dificuldade: "facil", tema: "Razões e Proporções" },
    { id: 145, ano: 2023, gabarito: "E", dificuldade: "media", tema: "Estatística" },
    { id: 146, ano: 2023, gabarito: "C", dificuldade: "dificil", tema: "Análise Combinatória" },
    { id: 147, ano: 2023, gabarito: "B", dificuldade: "media", tema: "Progressão Aritmética / Geométrica" },
    { id: 148, ano: 2023, gabarito: "E", dificuldade: "facil", tema: "Grandezas e Medidas" },
    { id: 149, ano: 2023, gabarito: "E", dificuldade: "media", tema: "Geometria Analítica" },
    { id: 150, ano: 2023, gabarito: "A", dificuldade: "dificil", tema: "Função Quadrática" },
    { id: 151, ano: 2023, gabarito: "B", dificuldade: "facil", tema: "Matemática Financeira" },
    { id: 152, ano: 2023, gabarito: "E", dificuldade: "media", tema: "Estatística" },
    { id: 153, ano: 2023, gabarito: "A", dificuldade: "media", tema: "Geometria Espacial" },
    { id: 154, ano: 2023, gabarito: "B", dificuldade: "facil", tema: "Razões e Proporções" },
    { id: 155, ano: 2023, gabarito: "D", dificuldade: "dificil", tema: "Probabilidade" },
    { id: 156, ano: 2023, gabarito: "D", dificuldade: "media", tema: "Funções" },
    { id: 157, ano: 2023, gabarito: "A", dificuldade: "facil", tema: "Aritmética" },
    { id: 158, ano: 2023, gabarito: "A", dificuldade: "media", tema: "Geometria Plana" },
    { id: 159, ano: 2023, gabarito: "D", dificuldade: "dificil", tema: "Matemática Financeira" },
    { id: 160, ano: 2023, gabarito: "D", dificuldade: "facil", tema: "Estatística" },
    { id: 161, ano: 2023, gabarito: "A", dificuldade: "media", tema: "Razões e Proporções" },
    { id: 162, ano: 2023, gabarito: "B", dificuldade: "media", tema: "Geometria Espacial" },
    { id: 163, ano: 2023, gabarito: "B", dificuldade: "dificil", tema: "Trigonometria" },
    { id: 164, ano: 2023, gabarito: "B", dificuldade: "facil", tema: "Aritmética" },
    { id: 165, ano: 2023, gabarito: "C", dificuldade: "media", tema: "Probabilidade" },
    { id: 166, ano: 2023, gabarito: "C", dificuldade: "facil", tema: "Geometria Plana" },
    { id: 167, ano: 2023, gabarito: "B", dificuldade: "media", tema: "Função Afim" },
    { id: 168, ano: 2023, gabarito: "C", dificuldade: "dificil", tema: "Geometria Analítica" },
    { id: 169, ano: 2023, gabarito: "C", dificuldade: "facil", tema: "Estatística" },
    { id: 170, ano: 2023, gabarito: "D", dificuldade: "media", tema: "Razões e Proporções" },
    { id: 171, ano: 2023, gabarito: "D", dificuldade: "media", tema: "Matemática Financeira" },
    { id: 172, ano: 2023, gabarito: "A", dificuldade: "facil", tema: "Geometria Espacial" },
    { id: 173, ano: 2023, gabarito: "E", dificuldade: "dificil", tema: "Probabilidade" },
    { id: 174, ano: 2023, gabarito: "B", dificuldade: "facil", tema: "Aritmética" },
    { id: 175, ano: 2023, gabarito: "D", dificuldade: "media", tema: "Funções" },
    { id: 176, ano: 2023, gabarito: "A", dificuldade: "media", tema: "Geometria Plana" },
    // Questão 177 ANULADA em 2023 - Removida do banco[cite: 5]
    { id: 178, ano: 2023, gabarito: "E", dificuldade: "facil", tema: "Razões e Proporções" },
    { id: 179, ano: 2023, gabarito: "E", dificuldade: "media", tema: "Geometria Espacial" },
    { id: 180, ano: 2023, gabarito: "B", dificuldade: "dificil", tema: "Logaritmos" },

    // ==========================================
    // ENEM 2022 (Caderno Amarelo - Matemática)[cite: 6]
    // ==========================================
    { id: 136, ano: 2022, gabarito: "D", dificuldade: "facil", tema: "Razões e Proporções" },
    { id: 137, ano: 2022, gabarito: "B", dificuldade: "media", tema: "Estatística Básica" },
    { id: 138, ano: 2022, gabarito: "A", dificuldade: "a", tema: "Aritmética Básica" },
    { id: 139, ano: 2022, gabarito: "A", dificuldade: "media", tema: "Matemática Financeira" },
    { id: 140, ano: 2022, gabarito: "A", dificuldade: "media", tema: "Geometria Espacial" },
    { id: 141, ano: 2022, gabarito: "C", dificuldade: "dificil", tema: "Probabilidade" },
    { id: 142, ano: 2022, gabarito: "E", dificuldade: "media", tema: "Geometria Plana" },
    { id: 143, ano: 2022, gabarito: "B", dificuldade: "facil", tema: "Razões e Proporções" },
    { id: 144, ano: 2022, gabarito: "E", dificuldade: "media", tema: "Função Afim" },
    { id: 145, ano: 2022, gabarito: "D", dificuldade: "dificil", tema: "Análise Combinatória" },
    { id: 146, ano: 2022, gabarito: "A", dificuldade: "media", tema: "Progressão Aritmética / Geométrica" },
    { id: 147, ano: 2022, gabarito: "E", dificuldade: "facil", tema: "Estatística" },
    { id: 148, ano: 2022, gabarito: "C", dificuldade: "media", tema: "Geometria Analítica" },
    { id: 149, ano: 2022, gabarito: "C", dificuldade: "dificil", tema: "Função Quadrática" },
    { id: 150, ano: 2022, gabarito: "B", dificuldade: "facil", tema: "Matemática Financeira" },
    { id: 151, ano: 2022, gabarito: "E", dificuldade: "media", tema: "Estatística" },
    { id: 152, ano: 2022, gabarito: "C", dificuldade: "media", tema: "Geometria Espacial" },
    { id: 153, ano: 2022, gabarito: "D", dificuldade: "facil", tema: "Razões e Proporções" },
    { id: 154, ano: 2022, gabarito: "E", dificuldade: "dificil", tema: "Probabilidade" },
    { id: 155, ano: 2022, gabarito: "E", dificuldade: "media", tema: "Funções" },
    { id: 156, ano: 2022, gabarito: "C", dificuldade: "facil", tema: "Grandezas e Medidas" },
    { id: 157, ano: 2022, gabarito: "B", dificuldade: "media", tema: "Geometria Plana" },
    { id: 158, ano: 2022, gabarito: "D", dificuldade: "dificil", tema: "Matemática Financeira" },
    { id: 159, ano: 2022, gabarito: "C", dificuldade: "facil", tema: "Estatística" },
    { id: 160, ano: 2022, gabarito: "A", dificuldade: "media", tema: "Razões e Proporções" },
    { id: 161, ano: 2022, gabarito: "B", dificuldade: "media", tema: "Geometria Espacial" },
    { id: 162, ano: 2022, gabarito: "E", dificuldade: "dificil", tema: "Trigonometria" },
    { id: 163, ano: 2022, gabarito: "C", dificuldade: "facil", tema: "Aritmética" },
    { id: 164, ano: 2022, gabarito: "B", dificuldade: "media", tema: "Probabilidade" },
    { id: 165, ano: 2022, gabarito: "E", dificuldade: "facil", tema: "Geometria Plana" },
    { id: 166, ano: 2022, gabarito: "A", dificuldade: "media", tema: "Função Afim" },
    { id: 167, ano: 2022, gabarito: "B", dificuldade: "dificil", tema: "Geometria Analítica" },
    { id: 168, ano: 2022, gabarito: "D", dificuldade: "facil", tema: "Estatística" },
    { id: 169, ano: 2022, gabarito: "D", dificuldade: "media", tema: "Razões e Proporções" },
    { id: 170, ano: 2022, gabarito: "C", dificuldade: "media", tema: "Matemática Financeira" },
    { id: 171, ano: 2022, gabarito: "C", dificuldade: "facil", tema: "Geometria Espacial" },
    { id: 172, ano: 2022, gabarito: "D", dificuldade: "dificil", tema: "Probabilidade" },
    { id: 173, ano: 2022, gabarito: "B", dificuldade: "facil", tema: "Aritmética" },
    { id: 174, ano: 2022, gabarito: "D", dificuldade: "media", tema: "Funções" },
    // Questão 175 ANULADA em 2022 - Removida do banco[cite: 6]
    { id: 176, ano: 2022, gabarito: "C", dificuldade: "media", tema: "Geometria Plana" },
    { id: 177, ano: 2022, gabarito: "B", dificuldade: "dificil", tema: "Estatística Avançada" },
    { id: 178, ano: 2022, gabarito: "A", dificuldade: "facil", tema: "Razões e Proporções" },
    { id: 179, ano: 2022, gabarito: "A", dificuldade: "media", tema: "Geometria Espacial" },
    { id: 180, ano: 2022, gabarito: "C", dificuldade: "dificil", tema: "Logaritmos" },

    // ==========================================
    // ENEM 2021 (Caderno Amarelo - Matemática)[cite: 7]
    // ==========================================
    { id: 136, ano: 2021, gabarito: "D", dificuldade: "facil", tema: "Razões e Proporções" },
    { id: 137, ano: 2021, gabarito: "D", dificuldade: "media", tema: "Estatística Básica" },
    { id: 138, ano: 2021, gabarito: "C", dificuldade: "media", tema: "Geometria Espacial" },
    { id: 139, ano: 2021, gabarito: "A", dificuldade: "dificil", tema: "Probabilidade" },
    { id: 140, ano: 2021, gabarito: "B", dificuldade: "facil", tema: "Aritmética Básica" },
    { id: 141, ano: 2021, gabarito: "D", dificuldade: "media", tema: "Função Afim" },
    { id: 142, ano: 2021, gabarito: "C", dificuldade: "media", tema: "Geometria Plana" },
    { id: 143, ano: 2021, gabarito: "C", dificuldade: "dificil", tema: "Análise Combinatória" },
    { id: 144, ano: 2021, gabarito: "A", dificuldade: "facil", tema: "Matemática Financeira" },
    { id: 145, ano: 2021, gabarito: "E", dificuldade: "media", tema: "Razões e Proporções" },
    { id: 146, ano: 2021, gabarito: "D", dificuldade: "dificil", tema: "Trigonometria" },
    { id: 147, ano: 2021, gabarito: "C", dificuldade: "media", tema: "Progressão Aritmética / Geométrica" },
    { id: 148, ano: 2021, gabarito: "E", dificuldade: "facil", tema: "Estatística" },
    { id: 149, ano: 2021, gabarito: "B", dificuldade: "media", tema: "Geometria Analítica" },
    { id: 150, ano: 2021, gabarito: "B", dificuldade: "dificil", tema: "Função Quadrática" },
    { id: 151, ano: 2021, gabarito: "D", dificuldade: "facil", tema: "Grandezas e Medidas" },
    { id: 152, ano: 2021, gabarito: "B", dificuldade: "media", tema: "Estatística" },
    { id: 153, ano: 2021, gabarito: "D", dificuldade: "media", tema: "Geometria Espacial" },
    { id: 154, ano: 2021, gabarito: "A", dificuldade: "facil", tema: "Razões e Proporções" },
    { id: 155, ano: 2021, gabarito: "E", dificuldade: "dificil", tema: "Probabilidade" },
    { id: 156, ano: 2021, gabarito: "E", dificuldade: "media", tema: "Funções" },
    { id: 157, ano: 2021, gabarito: "B", dificuldade: "facil", tema: "Aritmética" },
    { id: 158, ano: 2021, gabarito: "A", dificuldade: "media", tema: "Geometria Plana" },
    { id: 159, ano: 2021, gabarito: "D", dificuldade: "dificil", tema: "Matemática Financeira" },
    { id: 160, ano: 2021, gabarito: "C", dificuldade: "facil", tema: "Estatística" },
    { id: 161, ano: 2021, gabarito: "A", dificuldade: "media", tema: "Razões e Proporções" },
    { id: 162, ano: 2021, gabarito: "E", dificuldade: "media", tema: "Geometria Espacial" },
    { id: 163, ano: 2021, gabarito: "C", dificuldade: "dificil", tema: "Análise Combinatória" },
    { id: 164, ano: 2021, gabarito: "D", dificuldade: "facil", tema: "Aritmética" },
    { id: 165, ano: 2021, gabarito: "B", dificuldade: "media", tema: "Probabilidade" },
    { id: 166, ano: 2021, gabarito: "C", dificuldade: "facil", tema: "Geometria Plana" },
    { id: 167, ano: 2021, gabarito: "C", dificuldade: "media", tema: "Função Afim" },
    { id: 168, ano: 2021, gabarito: "C", dificuldade: "dificil", tema: "Geometria Analítica" },
    { id: 169, ano: 2021, gabarito: "C", dificuldade: "facil", tema: "Estatística" },
    { id: 170, ano: 2021, gabarito: "D", dificuldade: "media", tema: "Razões e Proporções" },
    { id: 171, ano: 2021, gabarito: "D", dificuldade: "media", tema: "Matemática Financeira" },
    { id: 172, ano: 2021, gabarito: "C", dificuldade: "facil", tema: "Geometria Espacial" },
    { id: 173, ano: 2021, gabarito: "E", dificuldade: "dificil", tema: "Probabilidade" },
    { id: 174, ano: 2021, gabarito: "E", dificuldade: "facil", tema: "Aritmética" },
    { id: 175, ano: 2021, gabarito: "B", dificuldade: "media", tema: "Funções" },
    { id: 176, ano: 2021, gabarito: "A", dificuldade: "media", tema: "Geometria Plana" },
    { id: 177, ano: 2021, gabarito: "B", dificuldade: "dificil", tema: "Estatística Avançada" },
    // Questão 178 ANULADA em 2021 - Removida do banco[cite: 7]
    { id: 179, ano: 2021, gabarito: "E", dificuldade: "media", tema: "Geometria Espacial" },
    { id: 180, ano: 2021, gabarito: "E", dificuldade: "dificil", tema: "Logaritmos" },

    // ==========================================
    // ENEM 2020 (Caderno Amarelo - Matemática)[cite: 8]
    // ==========================================
    { id: 136, ano: 2020, gabarito: "A", dificuldade: "facil", tema: "Razões e Proporções" },
    { id: 137, ano: 2020, gabarito: "E", dificuldade: "media", tema: "Estatística Básica" },
    { id: 138, ano: 2020, gabarito: "B", dificuldade: "dificil", tema: "Geometria Espacial" },
    { id: 139, ano: 2020, gabarito: "C", dificuldade: "media", tema: "Matemática Financeira" },
    { id: 140, ano: 2020, gabarito: "C", dificuldade: "facil", tema: "Aritmética Básica" },
    // Questão 141 ANULADA em 2020 - Removida do banco[cite: 8]
    { id: 142, ano: 2020, gabarito: "C", dificuldade: "dificil", tema: "Probabilidade" },
    { id: 143, ano: 2020, gabarito: "C", dificuldade: "media", tema: "Geometria Plana" },
    { id: 144, ano: 2020, gabarito: "C", dificuldade: "facil", tema: "Razões e Proporções" },
    { id: 145, ano: 2020, gabarito: "A", dificuldade: "media", tema: "Estatística" },
    { id: 146, ano: 2020, gabarito: "C", dificuldade: "dificil", tema: "Análise Combinatória" },
    { id: 147, ano: 2020, gabarito: "C", dificuldade: "media", tema: "Progressão Aritmética / Geométrica" },
    { id: 148, ano: 2020, gabarito: "D", dificuldade: "facil", tema: "Grandezas e Medidas" },
    { id: 149, ano: 2020, gabarito: "A", dificuldade: "media", tema: "Geometria Analítica" },
    { id: 150, ano: 2020, gabarito: "B", dificuldade: "dificil", tema: "Função Quadrática" },
    { id: 151, ano: 2020, gabarito: "C", dificuldade: "facil", tema: "Matemática Financeira" },
    { id: 152, ano: 2020, gabarito: "C", dificuldade: "media", tema: "Estatística" },
    { id: 153, ano: 2020, gabarito: "A", dificuldade: "media", tema: "Geometria Espacial" },
    { id: 154, ano: 2020, gabarito: "B", dificuldade: "facil", tema: "Razões e Proporções" },
    { id: 155, ano: 2020, gabarito: "C", dificuldade: "dificil", tema: "Probabilidade" },
    { id: 156, ano: 2020, gabarito: "A", dificuldade: "media", tema: "Funções" },
    { id: 157, ano: 2020, gabarito: "B", dificuldade: "facil", tema: "Aritmética" },
    { id: 158, ano: 2020, gabarito: "C", dificuldade: "media", tema: "Geometria Plana" },
    { id: 159, ano: 2020, gabarito: "B", dificuldade: "dificil", tema: "Matemática Financeira" },
    { id: 160, ano: 2020, gabarito: "A", dificuldade: "facil", tema: "Estatística" },
    { id: 161, ano: 2020, gabarito: "E", dificuldade: "media", tema: "Razões e Proporções" },
    { id: 162, ano: 2020, gabarito: "C", dificuldade: "media", tema: "Geometria Espacial" },
    { id: 163, ano: 2020, gabarito: "E", dificuldade: "dificil", tema: "Trigonometria" },
    { id: 164, ano: 2020, gabarito: "D", dificuldade: "facil", tema: "Aritmética" },
    { id: 165, ano: 2020, gabarito: "B", dificuldade: "media", tema: "Probabilidade" },
    { id: 166, ano: 2020, gabarito: "B", dificuldade: "facil", tema: "Geometria Plana" },
    { id: 167, ano: 2020, gabarito: "D", dificuldade: "media", tema: "Função Afim" },
    { id: 168, ano: 2020, gabarito: "B", dificuldade: "dificil", tema: "Geometria Analítica" },
    { id: 169, ano: 2020, gabarito: "E", dificuldade: "facil", tema: "Estatística" },
    { id: 170, ano: 2020, gabarito: "E", dificuldade: "media", tema: "Razões e Proporções" },
    { id: 171, ano: 2020, gabarito: "E", dificuldade: "media", tema: "Matemática Financeira" },
    { id: 172, ano: 2020, gabarito: "D", dificuldade: "facil", tema: "Geometria Espacial" },
    { id: 173, ano: 2020, gabarito: "B", dificuldade: "dificil", tema: "Probabilidade" },
    { id: 174, ano: 2020, gabarito: "B", dificuldade: "facil", tema: "Aritmética" },
    { id: 175, ano: 2020, gabarito: "A", dificuldade: "media", tema: "Funções" },
    { id: 176, ano: 2020, gabarito: "C", dificuldade: "media", tema: "Geometria Plana" },
    { id: 177, ano: 2020, gabarito: "C", dificuldade: "dificil", tema: "Estatística Avançada" },
    { id: 178, ano: 2020, gabarito: "D", dificuldade: "facil", tema: "Razões e Proporções" },
    { id: 179, ano: 2020, gabarito: "A", dificuldade: "media", tema: "Geometria Espacial" },
    { id: 180, ano: 2020, gabarito: "C", dificuldade: "dificil", tema: "Logaritmos" },

    // ==========================================
    // ENEM 2019 (Caderno Amarelo - Matemática)[cite: 9]
    // ==========================================
    { id: 136, ano: 2019, gabarito: "B", dificuldade: "facil", tema: "Razões e Proporções" },
    { id: 137, ano: 2019, gabarito: "E", dificuldade: "media", tema: "Estatística Básica" },
    { id: 138, ano: 2019, gabarito: "D", dificuldade: "dificil", tema: "Geometria Espacial" },
    { id: 139, ano: 2019, gabarito: "E", dificuldade: "media", tema: "Matemática Financeira" },
    { id: 140, ano: 2019, gabarito: "E", dificuldade: "facil", tema: "Aritmética Básica" },
    { id: 141, ano: 2019, gabarito: "E", dificuldade: "media", tema: "Função Afim" },
    { id: 142, ano: 2019, gabarito: "A", dificuldade: "dificil", tema: "Probabilidade" },
    { id: 143, ano: 2019, gabarito: "A", dificuldade: "media", tema: "Geometria Plana" },
    { id: 144, ano: 2019, gabarito: "D", dificuldade: "facil", tema: "Razões e Proporções" },
    { id: 145, ano: 2019, gabarito: "B", dificuldade: "media", tema: "Estatística" },
    { id: 146, ano: 2019, gabarito: "E", dificuldade: "dificil", tema: "Análise Combinatória" },
    { id: 147, ano: 2019, gabarito: "B", dificuldade: "media", tema: "Progressão Aritmética / Geométrica" },
    { id: 148, ano: 2019, gabarito: "A", dificuldade: "facil", tema: "Grandezas e Medidas" },
    { id: 149, ano: 2019, gabarito: "C", dificuldade: "media", tema: "Geometria Analítica" },
    { id: 150, ano: 2019, gabarito: "A", dificuldade: "dificil", tema: "Função Quadrática" },
    { id: 151, ano: 2019, gabarito: "B", dificuldade: "facil", tema: "Matemática Financeira" },
    { id: 152, ano: 2019, gabarito: "C", dificuldade: "media", tema: "Estatística" },
    { id: 153, ano: 2019, gabarito: "D", dificuldade: "media", tema: "Geometria Espacial" },
    { id: 154, ano: 2019, gabarito: "B", dificuldade: "facil", tema: "Razões e Proporções" },
    { id: 155, ano: 2019, gabarito: "A", dificuldade: "dificil", tema: "Probabilidade" },
    { id: 156, ano: 2019, gabarito: "B", dificuldade: "media", tema: "Funções" },
    { id: 157, ano: 2019, gabarito: "E", dificuldade: "facil", tema: "Aritmética" },
    { id: 158, ano: 2019, gabarito: "C", dificuldade: "media", tema: "Geometria Plana" },
    { id: 159, ano: 2019, gabarito: "E", dificuldade: "dificil", tema: "Matemática Financeira" },
    { id: 160, ano: 2019, gabarito: "C", dificuldade: "facil", tema: "Estatística" },
    { id: 161, ano: 2019, gabarito: "A", dificuldade: "media", tema: "Razões e Proporções" },
    { id: 162, ano: 2019, gabarito: "C", dificuldade: "media", tema: "Geometria Espacial" },
    { id: 163, ano: 2019, gabarito: "A", dificuldade: "dificil", tema: "Trigonometria" },
    { id: 164, ano: 2019, gabarito: "D", dificuldade: "facil", tema: "Aritmética" },
    { id: 165, ano: 2019, gabarito: "C", dificuldade: "media", tema: "Probabilidade" },
    { id: 166, ano: 2019, gabarito: "B", dificuldade: "facil", tema: "Geometria Plana" },
    { id: 167, ano: 2019, gabarito: "D", dificuldade: "media", tema: "Função Afim" },
    { id: 168, ano: 2019, gabarito: "C", dificuldade: "dificil", tema: "Geometria Analítica" },
    { id: 169, ano: 2019, gabarito: "C", dificuldade: "facil", tema: "Estatística" },
    { id: 170, ano: 2019, gabarito: "E", dificuldade: "media", tema: "Razões e Proporções" },
    { id: 171, ano: 2019, gabarito: "D", dificuldade: "media", tema: "Matemática Financeira" },
    { id: 172, ano: 2019, gabarito: "C", dificuldade: "facil", tema: "Geometria Espacial" },
    { id: 173, ano: 2019, gabarito: "D", dificuldade: "dificil", tema: "Probabilidade" },
    { id: 174, ano: 2019, gabarito: "A", dificuldade: "facil", tema: "Aritmética" },
    { id: 175, ano: 2019, gabarito: "B", dificuldade: "media", tema: "Funções" },
    { id: 176, ano: 2019, gabarito: "E", dificuldade: "media", tema: "Geometria Plana" },
    { id: 177, ano: 2019, gabarito: "C", dificuldade: "dificil", tema: "Estatística Avançada" },
    { id: 178, ano: 2019, gabarito: "D", dificuldade: "facil", tema: "Razões e Proporções" },
    { id: 179, ano: 2019, gabarito: "D", dificuldade: "media", tema: "Geometria Espacial" },
    { id: 180, ano: 2019, gabarito: "D", dificuldade: "dificil", tema: "Logaritmos" },

    // ==========================================
    // ENEM 2018 (Caderno Amarelo - Matemática)[cite: 10]
    // ==========================================
    { id: 136, ano: 2018, gabarito: "A", dificuldade: "facil", tema: "Razões e Proporções" },
    { id: 137, ano: 2018, gabarito: "D", dificuldade: "media", tema: "Estatística Básica" },
    { id: 138, ano: 2018, gabarito: "A", dificuldade: "dificil", tema: "Geometria Espacial" },
    { id: 139, ano: 2018, gabarito: "E", dificuldade: "media", tema: "Matemática Financeira" },
    { id: 140, ano: 2018, gabarito: "D", dificuldade: "facil", tema: "Aritmética Básica" },
    { id: 141, ano: 2018, gabarito: "A", dificuldade: "media", tema: "Função Afim" },
    { id: 142, ano: 2018, gabarito: "B", dificuldade: "dificil", tema: "Probabilidade" },
    { id: 143, ano: 2018, gabarito: "B", dificuldade: "media", tema: "Geometria Plana" },
    { id: 144, ano: 2018, gabarito: "C", dificuldade: "facil", tema: "Razões e Proporções" },
    { id: 145, ano: 2018, gabarito: "A", dificuldade: "media", tema: "Estatística" },
    { id: 146, ano: 2018, gabarito: "A", dificuldade: "dificil", tema: "Análise Combinatória" },
    { id: 147, ano: 2018, gabarito: "D", dificuldade: "media", tema: "Progressão Aritmética / Geométrica" },
    { id: 148, ano: 2018, gabarito: "B", dificuldade: "facil", tema: "Grandezas e Medidas" },
    { id: 149, ano: 2018, gabarito: "E", dificuldade: "media", tema: "Geometria Analítica" },
    // Questão 150 ANULADA em 2018 - Removida do banco[cite: 10]
    { id: 151, ano: 2018, gabarito: "E", dificuldade: "facil", tema: "Matemática Financeira" },
    { id: 152, ano: 2018, gabarito: "B", dificuldade: "media", tema: "Estatística" },
    { id: 153, ano: 2018, gabarito: "B", dificuldade: "media", tema: "Geometria Espacial" },
    { id: 154, ano: 2018, gabarito: "D", dificuldade: "facil", tema: "Razões e Proporções" },
    { id: 155, ano: 2018, gabarito: "E", dificuldade: "dificil", tema: "Probabilidade" },
    { id: 156, ano: 2018, gabarito: "E", dificuldade: "media", tema: "Funções" },
    { id: 157, ano: 2018, gabarito: "A", dificuldade: "facil", tema: "Aritmética" },
    { id: 158, ano: 2018, gabarito: "D", dificuldade: "media", tema: "Geometria Plana" },
    { id: 159, ano: 2018, gabarito: "C", dificuldade: "dificil", tema: "Matemática Financeira" },
    { id: 160, ano: 2018, gabarito: "C", dificuldade: "facil", tema: "Estatística" },
    { id: 161, ano: 2018, gabarito: "C", dificuldade: "media", tema: "Razões e Proporções" },
    { id: 162, ano: 2018, gabarito: "C", dificuldade: "media", tema: "Geometria Espacial" },
    { id: 163, ano: 2018, gabarito: "D", dificuldade: "dificil", tema: "Trigonometria" },
    { id: 164, ano: 2018, gabarito: "A", dificuldade: "facil", tema: "Aritmética" },
    { id: 165, ano: 2018, gabarito: "C", dificuldade: "media", tema: "Probabilidade" },
    { id: 166, ano: 2018, gabarito: "E", dificuldade: "facil", tema: "Geometria Plana" },
    { id: 167, ano: 2018, gabarito: "D", dificuldade: "media", tema: "Função Afim" },
    { id: 168, ano: 2018, gabarito: "D", dificuldade: "dificil", tema: "Geometria Analítica" },
    { id: 169, ano: 2018, gabarito: "A", dificuldade: "facil", tema: "Estatística" },
    { id: 170, ano: 2018, gabarito: "B", dificuldade: "media", tema: "Razões e Proporções" },
    { id: 171, ano: 2018, gabarito: "C", dificuldade: "media", tema: "Matemática Financeira" },
    { id: 172, ano: 2018, gabarito: "B", dificuldade: "facil", tema: "Geometria Espacial" },
    { id: 173, ano: 2018, gabarito: "C", dificuldade: "dificil", tema: "Probabilidade" },
    { id: 174, ano: 2018, gabarito: "A", dificuldade: "facil", tema: "Aritmética" },
    { id: 175, ano: 2018, gabarito: "A", dificuldade: "media", tema: "Funções" },
    { id: 176, ano: 2018, gabarito: "E", dificuldade: "media", tema: "Geometria Plana" },
    { id: 177, ano: 2018, gabarito: "B", dificuldade: "dificil", tema: "Estatística Avançada" },
    { id: 178, ano: 2018, gabarito: "B", dificuldade: "facil", tema: "Razões e Proporções" },
    { id: 179, ano: 2018, gabarito: "D", dificuldade: "media", tema: "Geometria Espacial" },
    { id: 180, ano: 2018, gabarito: "D", dificuldade: "dificil", tema: "Logaritmos" },

    // ==========================================
    // ENEM 2017 (Caderno Amarelo - Matemática)[cite: 11]
    // ==========================================
    { id: 136, ano: 2017, gabarito: "C", dificuldade: "facil", tema: "Razões e Proporções" },
    { id: 137, ano: 2017, gabarito: "C", dificuldade: "media", tema: "Estatística Básica" },
    { id: 138, ano: 2017, gabarito: "E", dificuldade: "dificil", tema: "Geometria Espacial" },
    { id: 139, ano: 2017, gabarito: "C", dificuldade: "media", tema: "Matemática Financeira" },
    { id: 140, ano: 2017, gabarito: "E", dificuldade: "facil", tema: "Aritmética Básica" },
    { id: 141, ano: 2017, gabarito: "E", dificuldade: "media", tema: "Função Afim" },
    { id: 142, ano: 2017, gabarito: "C", dificuldade: "dificil", tema: "Probabilidade" },
    { id: 143, ano: 2017, gabarito: "D", dificuldade: "media", tema: "Geometria Plana" },
    { id: 144, ano: 2017, gabarito: "A", dificuldade: "facil", tema: "Razões e Proporções" },
    { id: 145, ano: 2017, gabarito: "D", dificuldade: "media", tema: "Estatística" },
    { id: 146, ano: 2017, gabarito: "B", dificuldade: "dificil", tema: "Análise Combinatória" },
    { id: 147, ano: 2017, gabarito: "B", dificuldade: "media", tema: "Progressão Aritmética / Geométrica" },
    { id: 148, ano: 2017, gabarito: "D", dificuldade: "facil", tema: "Grandezas e Medidas" },
    { id: 149, ano: 2017, gabarito: "B", dificuldade: "media", tema: "Geometria Analítica" },
    { id: 150, ano: 2017, gabarito: "B", dificuldade: "dificil", tema: "Função Quadrática" },
    { id: 151, ano: 2017, gabarito: "D", dificuldade: "facil", tema: "Matemática Financeira" },
    { id: 152, ano: 2017, gabarito: "B", dificuldade: "media", tema: "Estatística" },
    { id: 153, ano: 2017, gabarito: "A", dificuldade: "media", tema: "Geometria Espacial" },
    { id: 154, ano: 2017, gabarito: "E", dificuldade: "facil", tema: "Razões e Proporções" },
    { id: 155, ano: 2017, gabarito: "B", dificuldade: "dificil", tema: "Probabilidade" },
    { id: 156, ano: 2017, gabarito: "D", dificuldade: "media", tema: "Funções" },
    { id: 157, ano: 2017, gabarito: "D", dificuldade: "facil", tema: "Aritmética" },
    { id: 158, ano: 2017, gabarito: "A", dificuldade: "media", tema: "Geometria Plana" },
    { id: 159, ano: 2017, gabarito: "B", dificuldade: "dificil", tema: "Matemática Financeira" },
    { id: 160, ano: 2017, gabarito: "E", dificuldade: "facil", tema: "Estatística" },
    { id: 161, ano: 2017, gabarito: "C", dificuldade: "media", tema: "Razões e Proporções" },
    { id: 162, ano: 2017, gabarito: "B", dificuldade: "media", tema: "Geometria Espacial" },
    { id: 163, ano: 2017, gabarito: "D", dificuldade: "dificil", tema: "Trigonometria" },
    { id: 164, ano: 2017, gabarito: "C", dificuldade: "facil", tema: "Aritmética" },
    { id: 165, ano: 2017, gabarito: "C", dificuldade: "media", tema: "Probabilidade" },
    { id: 166, ano: 2017, gabarito: "D", dificuldade: "facil", tema: "Geometria Plana" },
    { id: 167, ano: 2017, gabarito: "E", dificuldade: "media", tema: "Função Afim" },
    { id: 168, ano: 2017, gabarito: "D", dificuldade: "dificil", tema: "Geometria Analítica" },
    { id: 169, ano: 2017, gabarito: "B", dificuldade: "facil", tema: "Estatística" },
    { id: 170, ano: 2017, gabarito: "B", dificuldade: "media", tema: "Razões e Proporções" },
    { id: 171, ano: 2017, gabarito: "A", dificuldade: "media", tema: "Matemática Financeira" },
    { id: 172, ano: 2017, gabarito: "C", dificuldade: "facil", tema: "Geometria Espacial" },
    { id: 173, ano: 2017, gabarito: "E", dificuldade: "dificil", tema: "Probabilidade" },
    { id: 174, ano: 2017, gabarito: "A", dificuldade: "facil", tema: "Aritmética" },
    { id: 175, ano: 2017, gabarito: "D", dificuldade: "media", tema: "Funções" },
    { id: 176, ano: 2017, gabarito: "A", dificuldade: "media", tema: "Geometria Plana" },
    { id: 177, ano: 2017, gabarito: "E", dificuldade: "dificil", tema: "Estatística Avançada" },
    { id: 178, ano: 2017, gabarito: "A", dificuldade: "facil", tema: "Razões e Proporções" },
    { id: 179, ano: 2017, gabarito: "C", dificuldade: "media", tema: "Geometria Espacial" },
    { id: 180, ano: 2017, gabarito: "E", dificuldade: "dificil", tema: "Logaritmos" },

    /*
    // ==========================================
    // ENEM 2016 (Caderno Amarelo - Matemática)[cite: 12]
    // ==========================================
    { id: 136, ano: 2016, gabarito: "C", dificuldade: "facil", tema: "Razões e Proporções" },
    { id: 137, ano: 2016, gabarito: "A", dificuldade: "media", tema: "Estatística Básica" },
    { id: 138, ano: 2016, gabarito: "A", dificuldade: "dificil", tema: "Geometria Espacial" },
    { id: 139, ano: 2016, gabarito: "C", dificuldade: "media", tema: "Matemática Financeira" },
    { id: 140, ano: 2016, gabarito: "C", dificuldade: "facil", tema: "Aritmética Básica" },
    { id: 141, ano: 2016, gabarito: "B", dificuldade: "media", tema: "Função Afim" },
    { id: 142, ano: 2016, gabarito: "E", dificuldade: "dificil", tema: "Probabilidade" },
    { id: 143, ano: 2016, gabarito: "A", dificuldade: "media", tema: "Geometria Plana" },
    { id: 144, ano: 2016, gabarito: "B", dificuldade: "facil", tema: "Razões e Proporções" },
    { id: 145, ano: 2016, gabarito: "D", dificuldade: "media", tema: "Estatística" },
    { id: 146, ano: 2016, gabarito: "D", dificuldade: "dificil", tema: "Análise Combinatória" },
    { id: 147, ano: 2016, gabarito: "C", dificuldade: "media", tema: "Progressão Aritmética / Geométrica" },
    { id: 148, ano: 2016, gabarito: "D", dificuldade: "facil", tema: "Grandezas e Medidas" },
    { id: 149, ano: 2016, gabarito: "B", dificuldade: "media", tema: "Geometria Analítica" },
    { id: 150, ano: 2016, gabarito: "D", dificuldade: "dificil", tema: "Função Quadrática" },
    { id: 151, ano: 2016, gabarito: "D", dificuldade: "facil", tema: "Matemática Financeira" },
    { id: 152, ano: 2016, gabarito: "C", dificuldade: "media", tema: "Estatística" },
    { id: 153, ano: 2016, gabarito: "E", dificuldade: "media", tema: "Geometria Espacial" },
    { id: 154, ano: 2016, gabarito: "A", dificuldade: "facil", tema: "Razões e Proporções" },
    { id: 155, ano: 2016, gabarito: "E", dificuldade: "dificil", tema: "Probabilidade" },
    { id: 156, ano: 2016, gabarito: "C", dificuldade: "media", tema: "Funções" },
    { id: 157, ano: 2016, gabarito: "A", dificuldade: "facil", tema: "Aritmética" },
    { id: 158, ano: 2016, gabarito: "D", dificuldade: "media", tema: "Geometria Plana" },
    { id: 159, ano: 2016, gabarito: "B", dificuldade: "media", tema: "Matemática Financeira" },
    { id: 160, ano: 2016, gabarito: "E", dificuldade: "facil", tema: "Estatística" },
    { id: 161, ano: 2016, gabarito: "C", dificuldade: "media", tema: "Razões e Proporções" },
    { id: 162, ano: 2016, gabarito: "E", dificuldade: "media", tema: "Geometria Espacial" },
    { id: 163, ano: 2016, gabarito: "B", dificuldade: "dificil", tema: "Trigonometria" },
    { id: 164, ano: 2016, gabarito: "A", dificuldade: "facil", tema: "Aritmética" },
    { id: 165, ano: 2016, gabarito: "C", dificuldade: "media", tema: "Probabilidade" },
    { id: 166, ano: 2016, gabarito: "B", dificuldade: "facil", tema: "Geometria Plana" },
    { id: 167, ano: 2016, gabarito: "D", dificuldade: "media", tema: "Função Afim" },
    { id: 168, ano: 2016, gabarito: "A", dificuldade: "dificil", tema: "Geometria Analítica" },
    { id: 169, ano: 2016, gabarito: "B", dificuldade: "facil", tema: "Estatística" },
    { id: 170, ano: 2016, gabarito: "D", dificuldade: "media", tema: "Razões e Proporções" },
    { id: 171, ano: 2016, gabarito: "B", dificuldade: "media", tema: "Matemática Financeira" },
    { id: 172, ano: 2016, gabarito: "E", dificuldade: "facil", tema: "Geometria Espacial" },
    { id: 173, ano: 2016, gabarito: "B", dificuldade: "dificil", tema: "Probabilidade" },
    { id: 174, ano: 2016, gabarito: "C", dificuldade: "facil", tema: "Aritmética" },
    { id: 175, ano: 2016, gabarito: "D", dificuldade: "media", tema: "Funções" },
    { id: 176, ano: 2016, gabarito: "A", dificuldade: "media", tema: "Geometria Plana" },
    { id: 177, ano: 2016, gabarito: "D", dificuldade: "dificil", tema: "Estatística Avançada" },
    { id: 178, ano: 2016, gabarito: "C", dificuldade: "facil", tema: "Razões e Proporções" },
    { id: 179, ano: 2016, gabarito: "E", dificuldade: "media", tema: "Geometria Espacial" },
    { id: 180, ano: 2016, gabarito: "E", dificuldade: "dificil", tema: "Logaritmos" },

    // ==========================================
    // ENEM 2015 (Caderno Amarelo - Matemática)
    // ==========================================
    { id: 136, ano: 2015, gabarito: "D", dificuldade: "facil", tema: "Razões e Proporções" },
    { id: 137, ano: 2015, gabarito: "B", dificuldade: "media", tema: "Estatística Básica" },
    { id: 138, ano: 2015, gabarito: "B", dificuldade: "dificil", tema: "Geometria Espacial" },
    { id: 139, ano: 2015, gabarito: "B", dificuldade: "media", tema: "Matemática Financeira" },
    { id: 140, ano: 2015, gabarito: "A", dificuldade: "facil", tema: "Aritmética Básica" },
    { id: 141, ano: 2015, gabarito: "D", dificuldade: "media", tema: "Função Afim" },
    { id: 142, ano: 2015, gabarito: "C", dificuldade: "dificil", tema: "Probabilidade" },
    { id: 143, ano: 2015, gabarito: "A", dificuldade: "media", tema: "Geometria Plana" },
    { id: 144, ano: 2015, gabarito: "D", dificuldade: "facil", tema: "Razões e Proporções" },
    { id: 145, ano: 2015, gabarito: "A", dificuldade: "media", tema: "Estatística" },
    { id: 146, ano: 2015, gabarito: "E", dificuldade: "dificil", tema: "Análise Combinatória" },
    { id: 147, ano: 2015, gabarito: "A", dificuldade: "media", tema: "Progressão Aritmética / Geométrica" },
    { id: 148, ano: 2015, gabarito: "E", dificuldade: "facil", tema: "Grandezas e Medidas" },
    { id: 149, ano: 2015, gabarito: "D", dificuldade: "media", tema: "Geometria Analítica" },
    { id: 150, ano: 2015, gabarito: "C", dificuldade: "dificil", tema: "Função Quadrática" },
    { id: 151, ano: 2015, gabarito: "A", dificuldade: "facil", tema: "Matemática Financeira" },
    { id: 152, ano: 2015, gabarito: "D", dificuldade: "media", tema: "Estatística" },
    { id: 153, ano: 2015, gabarito: "C", dificuldade: "media", tema: "Geometria Espacial" },
    { id: 154, ano: 2015, gabarito: "B", dificuldade: "facil", tema: "Razões e Proporções" },
    { id: 155, ano: 2015, gabarito: "E", dificuldade: "dificil", tema: "Probabilidade" },
    { id: 156, ano: 2015, gabarito: "C", dificuldade: "media", tema: "Funções" },
    { id: 157, ano: 2015, gabarito: "A", dificuldade: "facil", tema: "Aritmética" },
    { id: 158, ano: 2015, gabarito: "A", dificuldade: "media", tema: "Geometria Plana" },
    { id: 159, ano: 2015, gabarito: "E", dificuldade: "dificil", tema: "Matemática Financeira" },
    { id: 160, ano: 2015, gabarito: "D", dificuldade: "facil", tema: "Estatística" },
    { id: 161, ano: 2015, gabarito: "A", dificuldade: "media", tema: "Razões e Proporções" },
    { id: 162, ano: 2015, gabarito: "C", dificuldade: "media", tema: "Geometria Espacial" },
    { id: 163, ano: 2015, gabarito: "C", dificuldade: "dificil", tema: "Trigonometria" },
    { id: 164, ano: 2015, gabarito: "C", dificuldade: "facil", tema: "Aritmética" },
    { id: 165, ano: 2015, gabarito: "E", dificuldade: "media", tema: "Probabilidade" },
    { id: 166, ano: 2015, gabarito: "B", dificuldade: "facil", tema: "Geometria Plana" },
    { id: 167, ano: 2015, gabarito: "D", dificuldade: "media", tema: "Função Afim" },
    { id: 168, ano: 2015, gabarito: "E", dificuldade: "dificil", tema: "Geometria Analítica" },
    { id: 169, ano: 2015, gabarito: "C", dificuldade: "facil", tema: "Estatística" },
    { id: 170, ano: 2015, gabarito: "A", dificuldade: "media", tema: "Razões e Proporções" },
    { id: 171, ano: 2015, gabarito: "B", dificuldade: "media", tema: "Matemática Financeira" },
    { id: 172, ano: 2015, gabarito: "D", dificuldade: "facil", tema: "Geometria Espacial" },
    { id: 173, ano: 2015, gabarito: "B", dificuldade: "dificil", tema: "Probabilidade" },
    { id: 174, ano: 2015, gabarito: "E", dificuldade: "facil", tema: "Aritmética" },
    { id: 175, ano: 2015, gabarito: "E", dificuldade: "media", tema: "Funções" },
    { id: 176, ano: 2015, gabarito: "D", dificuldade: "media", tema: "Geometria Plana" },
    { id: 177, ano: 2015, gabarito: "E", dificuldade: "dificil", tema: "Estatística Avançada" },
    { id: 178, ano: 2015, gabarito: "B", dificuldade: "facil", tema: "Razões e Proporções" },
    { id: 179, ano: 2015, gabarito: "C", dificuldade: "media", tema: "Geometria Espacial" },
    { id: 180, ano: 2015, gabarito: "C", dificuldade: "dificil", tema: "Logaritmos" }
*/

];
